##################################################################################################
##
##  Xilinx, Inc. 2010            www.xilinx.com
##  ÖÜÒ» 2ÔÂ 20 21:06:05 2017
##  Generated by MIG Version 4.0
##
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A100T-FGG676
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         0 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K128M16XX-15E
## Data Width: 16
## Time Period: 2500
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################


# PadFunction: IO_L1P_T0_AD4P_35
set_property IOSTANDARD LVCMOS33 [get_ports init_calib_complete]
set_property PACKAGE_PIN J25 [get_ports init_calib_complete]

#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dqs_p[0]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dqs_n[0]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dqs_p[1]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dqs_n[1]}]

#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[0]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[1]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[2]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[3]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[4]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[5]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[6]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[7]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[8]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[9]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[10]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[11]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[12]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[13]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[14]}]
#set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[15]}]

#set_property PACKAGE_PIN J26 [get_ports tg_compare_error]
#set_property IOSTANDARD LVCMOS33 [get_ports tg_compare_error]







